# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sequel", "~> 5.30"

gem "sqlite3", "~> 1.4"

gem "colorize", "~> 0.8.1"

gem "whirly", "~> 0.2.6"
